# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "nct6775" ];
  boot.extraModulePackages = [ ];

   boot.initrd.luks.devices."root" = {
     device = "/dev/disk/by-uuid/72175e17-e454-468e-b375-91b215f8a348";
   };

  environment.etc.crypttab.text = ''
    data /dev/disk/by-uuid/814a3c86-9694-4fcd-83ab-e58fb67e6f76 /etc/secrets/keyfile.bin
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/09d73ac5-eed3-4636-be67-225810ba40d4";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e74e6dea-ab4c-4285-acb1-45e26cb44ddc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BCE7-61C1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" "defaults" ];
  };

  fileSystems."/data/Work" = {
    device = "/dev/disk/by-uuid/6eb1533c-30aa-488d-8ffc-b8d26b30e64d";
    fsType = "ext4";
  };

  fileSystems."/data/Media" = {
    device = "/dev/disk/by-uuid/a70ba49b-ac12-4f15-9b43-d4b00a6607f3";
    fsType = "ext4";
  };

  swapDevices = [{ device = "/dev/disk/by-uuid/ec1f4aa6-0e0b-4c80-8bfe-4a750efd9543"; }];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
